# Generated by Django 5.0.6 on 2024-06-26 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='birthday',
            new_name='birthdate',
        ),
    ]
